version: 1
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/ExamplePipelinePlugin/MyPipelinePlugin/"
    update_schedule: "live"
    target_branch: "develop"
    default_reviewers:
    - tznind
  - package_manager: "dotnet:nuget"
    directory: "/ExampleUIPlugin/"
    update_schedule: "live"
    target_branch: "develop"
    default_reviewers:
    - tznind